# Generated by Django 2.2.2 on 2019-06-10 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=500)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('chatroom', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='chat_app.ChatRoom')),
                ('user_sender', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender_message', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
